# Generated by Django 5.1.2 on 2024-10-15 06:33

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex1', banjo.models.IntegerField(default=0)),
                ('hex2', banjo.models.IntegerField(default=0)),
                ('hex3', banjo.models.IntegerField(default=0)),
                ('hex4', banjo.models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
