# Generated by Django 5.1.2 on 2024-10-18 00:44

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='hex1',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='palette',
            name='hex2',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='palette',
            name='hex3',
            field=banjo.models.StringField(default=''),
        ),
        migrations.AlterField(
            model_name='palette',
            name='hex4',
            field=banjo.models.StringField(default=''),
        ),
    ]
