# Generated by Django 5.1.2 on 2024-10-18 00:52

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_palette_hex1_alter_palette_hex2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='tone',
            field=banjo.models.StringField(default=''),
        ),
    ]
