# Generated by Django 5.1.2 on 2024-10-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_palette_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='tone',
        ),
    ]
