# Generated by Django 5.1.2 on 2024-10-24 04:34

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_palette_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='keyword',
            field=banjo.models.StringField(default=''),
        ),
    ]
